# Generated by Django 6.0.1 on 2026-01-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField()),
                ('summary', models.JSONField()),
                ('csv_file', models.FileField(upload_to='datasets/')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
