# Generated by Django 6.0.1 on 2026-01-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_delete_existing_datasets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdataset',
            name='user',
        ),
    ]
