# Generated by Django 6.0.1 on 2026-01-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipmentdataset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdataset',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='datasets/'),
        ),
    ]
